### ISSUE TITLE
Deprecation warning in PHP >= 8.1

### ISSUE THREAD

**Issue by wiegertschouten** [elightup/admin-taxonomy-filter#7]
Hi there,

Thanks for this nice plugin. However, under PHP 8.1 and higher, I get the following deprecation warning in a post list when I use a taxonomy filter:

```
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /path/to/my/site/wp-content/plugins/admin-taxonomy-filter/inc/controller.php on line 53
```

This Stackoverflow answer might shed some light on how to fix this: https://stackoverflow.com/questions/69207368/constant-filter-sanitize-string-is-deprecated

If a PR is helpful, I can try and make one. Let me know.

**Comment by webexpr-dhenriet** [comment]
the plugin has been updated to version 1.0.3, but the deprecated warning is still displayed. Are there any plans to correct it?
This wouldn't be enough to fix the problem ?

```php
'selected' => htmlspecialchars(strip_tags(filter_input(INPUT_GET, $taxonomy->query_var))),
```
